[package]
name = "db-migrator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
anyhow = { version = "1.0", features = ["backtrace"] }
log = "0.4.16"
env_logger = "0.10.0"
chrono = { version = "0.4" }
toml = "0.7.5"
prettytable-rs = "0.10.0"
async-trait = "0.1"
hex = "0.4.3"
futures = "0.3"
tiberius = { version = "0.12.2" }
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "mysql"] }